# The name of the action
name: Run tests
# When the action is triggered
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop
      - master

# What to do when the action is triggered
jobs:
  # A job called 'build' - arbitrary
  test:
    # Run on a Ubuntu VM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python with Poetry
      - name: Set up Python with Poetry
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Install dependencies and Poetry
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Run migrations
        run: |
          poetry run python src/manage.py migrate
    

      # Move into the Django project folder (./app) and run pytest
      - name: Run tests
        working-directory: ./src
        run: |
          poetry run pytest --ds=main.settings
